# Introduction to julia David Sanders 

##  Sintaxis basica de julia

Vamos a ver una definicion básica de una funcion en julia, la cual compara un dato de entrada con un numero generado aleatoriamente.

In [1]:
function coin(p)
    r = rand()
    println(r)
    
    return r < p
end
function print_result(val)
    if val == true
        println("es mayor")
        else println("es menor")
    end
end


print_result (generic function with 1 method)

In [2]:
val=coin(5)

print_result(val)

0.1991365641818923
es mayor


In [3]:
f(x)=2x^2+3x+1
g(x)=f(x)-(2x+1)*(x+1)

g (generic function with 1 method)

In [4]:
f(3)

28

In [5]:
g(3.5)

0.0

#sustitucion de variable con $ 

In [6]:
name= "Danilo"
greeting ="Hello,$name"
println(greeting)

Hello,Danilo


# numerical types
    hay tipos de numeros con diferentes precisiones: tecleando float<Tab> o int<TAB>

In [7]:
a=Int8(1)
b=Int8(2)
a+b

3

In [8]:
typeof(ans)

Int8

#BigInt

In [9]:
10^5

100000

In [10]:
typeof(ans)

Int64

In [11]:
10^19

-8446744073709551616

In [12]:
ten=big(10)

10

In [13]:
ten^19

10000000000000000000

In [14]:
typeof(ans)

BigInt

In [15]:
i=Int8(10)

10

In [16]:
i*100

1000

In [17]:
typeof(ans)

Int64

In [18]:
typemax(Int8)

127

In [19]:
typemin(Int8)

-128

numeros complejos usando im para la parte imaginaria

In [20]:
a=7
c=(1+3.5im)*a

7.0 + 24.5im

In [21]:
c=(1+3.5im)*a

7.0 + 24.5im

In [22]:
conj(c) #conjugado de c

7.0 - 24.5im

In [23]:
c*conj(c)

649.25 + 0.0im

numeros racionales tambien pueden ser creados en julia usando el operator //

In [24]:
3//4 + 5//6

19//12

los operadores son una manera conveniente de escribir funciones

In [25]:
//(3,4)

3//4

In [26]:
typeof(ans)

Rational{Int64}

## Evaluación de un condicional

In [27]:
a= 3
a<5 && println("small") #evalua la segunda sentencia solo si se cumple la primera

small


In [28]:
a<5 || println("small") #estructura si-no-entonces

true

In [29]:
val=3
val == 3 ? println("Hello") : println("Not true") # evalua condición a==3 y ejecuta instrucción segun sea el caso

Hello


In [30]:
val=8
val == 3 ? println("Hello") : println("Not true") # evalua condición a==3 y ejecuta instrucción segun sea el caso 

Not true


## Comprensión arreglos

Definicion de arreglo.

In [31]:
l=[3,4,5]

3-element Vector{Int64}:
 3
 4
 5

Los arreglos pueden contener distintos tipos de datos

In [32]:
α=5

5

In [33]:
Ar=[3.0, "Hello", 2, α]

4-element Vector{Any}:
 3.0
  "Hello"
 2
 5

In [34]:
squares = [ i^2 for i = 1:2:10]

5-element Vector{Int64}:
  1
  9
 25
 49
 81

### Matrices

In [35]:
sums = [i+j for i=1:5, j=1:5]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [36]:
Mat_random = rand(2,2)

2×2 Matrix{Float64}:
 0.474727  0.0656445
 0.689585  0.0744643

Multiplicacion de matrices

LAmultiplicacion de matrices deben seguir las reglas de conformidad para que la función (*) pueda aplica un metodo.

In [37]:
Mat_1 = [2 1;1 1]

2×2 Matrix{Int64}:
 2  1
 1  1

In [38]:
Mat_2 = [1 1 ; 2 2]

2×2 Matrix{Int64}:
 1  1
 2  2

Usando *@which* podemos saber especificamente que metodo de una funcion se utilizó con base en la dedución de tipo de dato de entrada.

In [39]:
@which Mat_1 * Mat_2


*(A::AbstractMatrix, B::AbstractMatrix) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:151

In [40]:
*(Mat_1,Mat_2) #Otra forma de definir la funcion de multiplicacion de matrices

2×2 Matrix{Int64}:
 4  4
 3  3

## Funciones

Las funciones pueden  ser definidas usando de la sintaxis corta o un formato mas largo:

-Declaración completa:

In [41]:
function duplicate(x::Int64) 
    2*x # En este caso no es necesario explicitamente el return
    end # julia interpreta que es calcula y regresa un valor de salida

duplicate (generic function with 1 method)

-Declaración corta.

In [42]:
duplicar(x)=2*x

duplicar (generic function with 1 method)

In [43]:
duplicate(5)

10

In [44]:
duplicar(5)

10

Un caso particular con las cadenas de caracteres es que funciones como + ó * tienes metodos para operarlas, sin embargo debemos especificar el tipo en la funcion, de este modo podremos agregar a la definicion de la funcion un metodo nuevo para operar dichos valores, esto es:

In [45]:
s1= "Primer string "
s2="Segundo string"

"Segundo string"

In [46]:
import Base:+ #impotamos la funcion de la biblioteca para modificarla y agregar el metodo

In [47]:
+(s1::String, s2::String) = string(s1, s2)

+ (generic function with 209 methods)

Podemos definir los metodos que necesitemos a la función y lo notamos cuando visualizamos la salida, por ejemplo sumar un numero de tipo *float* y otro de tipo *int*.

In [48]:
+(a::Float64 , b::Int64)= a-b

+ (generic function with 210 methods)

In [49]:
s1+s2

"Primer string Segundo string"

## Despacho multiple

#### Las funciones despacharán (ejecutaran) distintos procesos (llamados métodos) según el tipo de variables que hayan sido insertados en la entrada (*inputs*)

Vamos a crear una funcion simple que realice una multiplicación

In [50]:
function mult(x,y)
    return x*y
end

mult (generic function with 1 method)

La salida de la ejecución (*output*) del metodo anterior nos muestra que es una funcion con un metodo dado por ("*"), con lo cual podemos evaluar:

In [51]:
mult(8.0,3.0)

24.0

In [52]:
mult("Buenos ","Dias")

"Buenos Dias"

Podemos evaluar cadenas de caracteres **string** gracias a que es un metodo de *.
La función *() posee distintos metodos de los que julia ejecuta cuando identifica el tipo de dato de entrada:
Podemos conocer mas de los metodos de una funcion usando : methods(nombre_funcion)

In [53]:
methods(*)

# 364 methods for generic function "*":
[1] *(x::T, y::T) where T<:Union{Int128, UInt128} in Base at int.jl:967
[2] *(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:88
[3] *(s1::Union{AbstractChar, AbstractString}, ss::Union{AbstractChar, AbstractString}...) in Base at strings/basic.jl:260
[4] *(d::Union{AbstractChar, AbstractString}, x::Missing) in Base at missing.jl:183
[5] *(c::Union{UInt16, UInt32, UInt8}, x::BigInt) in Base.GMP at gmp.jl:540
[6] *(c::Union{Int16, Int32, Int8}, x::BigInt) in Base.GMP at gmp.jl:542
[7] *(c::Union{UInt16, UInt32, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:397
[8] *(c::Union{Int16, Int32, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:405
[9] *(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:413
[10] *(A::StridedMatrix{T}, x::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:44
[11] *(A::StridedMatrix{var"#s861"} where var"#s861"<:Union{Float32, Float64}, B::StridedMatrix{var"#s860"} where var"#s860"<:Union{Float32, Float64, ComplexF32, ComplexF64}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:158
[12] *(A::StridedMatrix{var"#s861"} where var"#s861"<:Union{ComplexF32, ComplexF64}, B::StridedMatrix{var"#s860"} where var"#s860"<:Union{ComplexF32, ComplexF64}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:162
[13] *(α::Union{Real, Complex}, vt::Union{LinearAlgebra.Adjoint{var"#s861", var"#s8611"}, LinearAlgebra.Transpose{var"#s861", var"#s8611"}} where {var"#s861"<:Union{Real, Complex}, var"#s8611"<:(AbstractVector)}, C::AbstractMatrix{<:Union{Real, Complex}}, D::AbstractMatrix{<:Union{Real, Complex}}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:1172
[14] *(A::StridedMatrix{T} where T, Q::LinearAlgebra.AbstractQ) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\qr.jl:755
[15] *(A::StridedMatrix{T} where T, adjB::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.AbstractQ}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\qr.jl:802
[16] *(A::StridedVecOrMat, adjQ::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\lq.jl:266
[17] *(A::StridedVecOrMat, Q::LinearAlgebra.LQPackedQ) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\lq.jl:290
[18] *(A::Union{LinearAlgebra.Hermitian{T, S}, LinearAlgebra.Symmetric{T, S}} where {T, S}, B::Union{LinearAlgebra.Hermitian{T, S}, LinearAlgebra.Symmetric{T, S}} where {T, S}) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\symmetric.jl:576
[19] *(A::Union{LinearAlgebra.UnitUpperTriangular, LinearAlgebra.UpperTriangular}, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\bidiag.jl:639
[20] *(A::Union{LinearAlgebra.LowerTriangular, LinearAlgebra.UnitLowerTriangular}, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\bidiag.jl:648
[21] *(A::Union{LinearAlgebra.SymTridiagonal, LinearAlgebra.Tridiagonal}, B::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\bidiag.jl:657
[22] *(A::Union{LinearAlgebra.Bidiagonal, LinearAlgebra.Tridiagonal}, B::LinearAlgebra.Di

In [54]:
methods(mult)

# 1 method for generic function "mult":
[1] mult(x, y) in Main at In[50]:1

In [55]:
mult([2, 3, 4, 5],[7, 8, 1, 2])

LoadError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\base\operators.jl:655
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:44
  *(::StridedVecOrMat, ::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ}) at C:\Users\dan_x\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\lq.jl:266
  ...

**El error anterior surge debido a que *() no tiene un metodo definido para dichos valores, es decir los vectores**
En realidad, si tiene un metodo para multiplicarlos,sin embargo estos tendrian que cumplir con las reglas de conformidad de matrices 

In [56]:
multiplica(reshape([2, 3, 4, 5],(1,4)),[7, 8, 1, 2]) #convertimos el vector en una matriz de 1x4 para 
                                                     #poder realizar la operacion

LoadError: UndefVarError: multiplica not defined

In [57]:
reshape([2, 3, 4, 5],(1,4))

1×4 Matrix{Int64}:
 2  3  4  5

#### Podemos entender tambien el despacho multiple definiendo una función con el tipo de entrada de manera explicita, agregando en el argumento despues de la variable el tipo de dato de la siguiente forma *variables::tipo*

In [58]:
function func_tipo(x::Int64)
    println("$x es un dato de tipo entero de 64 bits Int64")
end

func_tipo (generic function with 1 method)

In [59]:
function func_tipo(x::String)
    println("$x es una cadena de caracteres, un dato de tipo String")
end

func_tipo (generic function with 2 methods)

In [60]:
function func_tipo(x::Float64)
    println("$x es un dato de tipo decimal o punto flotante de 64 bits Float64")
end

func_tipo (generic function with 3 methods)

En este ejemplo definimos la misma funcion tres veces con diferente dato de entrada mostrandonos en el *output* el cambio en el numero de metodos que ahora tiene, esto es, los tipos de datos que ahora recibe.

In [61]:
methods(func_tipo)

# 3 methods for generic function "func_tipo":
[1] func_tipo(x::Int64) in Main at In[58]:1
[2] func_tipo(x::String) in Main at In[59]:1
[3] func_tipo(x::Float64) in Main at In[60]:1

In [62]:
func_tipo(85)

85 es un dato de tipo entero de 64 bits Int64


In [63]:
func_tipo("Danilo")

Danilo es una cadena de caracteres, un dato de tipo String


 Cualquier otro tipo de dato distinto a los anteriores nos regresa un error, por ejemplo un valor boolean

In [64]:
func_tipo(true)

LoadError: MethodError: no method matching func_tipo(::Bool)
Closest candidates are:
  func_tipo(::Int64) at In[58]:1
  func_tipo(::String) at In[59]:1
  func_tipo(::Float64) at In[60]:1

**Ejercicio**: Define operaciones matematicas sobre un vector 2D. Define una particula con posicion y velocidad en 2D.Define una función de movimiento que actúa sobre una partícula para moverla durante un tiempo $\delta t$

Primero definimos un tipo de dato compuesto:

In [65]:
struct V2D #nuevo tipo
    x::Float64
    y::Float64
end

In [72]:
v = V2D(3,4)
w = V2D(8,6)

V2D(8.0, 6.0)

Puesto que no hay un metodo definido de suma para nuestro nuevo tipo de dato, creamos la "regla" para realizar la operación, como lo hicimos anteriormente para concatenar las cadenas.

In [75]:
import Base:+
+(v::V2D, w::V2D)= V2D(v.x+w.x, v.y+w.y)

+ (generic function with 211 methods)

In [76]:
v+w

V2D(11.0, 10.0)

Podemos tambien crear un metodo para multiplicar por un escalar nuestro dato tipo vector2D:

In [92]:
import Base:*
*(α::Number,ω::V2D) = V2D(α*ω.x, α*ω.y)

* (generic function with 366 methods)

In [95]:
v*5.0

V2D(15.0, 20.0)

In [113]:
Pkg.add("PyPlot")

   Resolving package versions...
   Installed PyPlot ─ v2.11.0
   Installed PyCall ─ v1.94.1
    Updating `C:\Users\dan_x\.julia\environments\v1.7\Project.toml`
  [d330b81b] + PyPlot v2.11.0
    Updating `C:\Users\dan_x\.julia\environments\v1.7\Manifest.toml`
  [438e738f] + PyCall v1.94.1
  [d330b81b] + PyPlot v2.11.0
    Building PyCall → `C:\Users\dan_x\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\53b8b07b721b77144a0fbbbc2675222ebf40a02d\build.log`
Precompiling project...
  ✓ PyCall
  ✓ PyPlot
  2 dependencies successfully precompiled in 7 seconds (217 already precompiled)


In [114]:
using PyPlot

┌ Info: Installing matplotlib via the Conda matplotlib package...
└ @ PyCall C:\Users\dan_x\.julia\packages\PyCall\ygXW2\src\PyCall.jl:719
┌ Info: Running `conda install -y matplotlib` in root environment
└ @ Conda C:\Users\dan_x\.julia\packages\Conda\x2UxR\src\Conda.jl:127


Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\dan_x\.julia\conda\3

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotli-1.0.9               |       h8ffe710_7          18 KB  conda-forge
    brotli-bin-1.0.9           |       h8ffe710_7          21 KB  conda-forge
    cycler-0.11.0              |     pyhd8ed1ab_0          10 KB  conda-forge
    fonttools-4.37.1           |  py310he2412df_0         1.7 MB  conda-forge
    freetype-2.12.1            |       h546665d_0         506 KB  conda-forge
    gettext-0.19.8.1           |    h5728263_1009         4.7 MB  conda-forge
    gli



lerc-4.0.0           | 190 KB    | ########## | 100% 
libiconv-1.17        | 698 KB    | ########## | 100% 
pyqt-5.15.7          | 4.7 MB    | ########## | 100% 
gstreamer-1.20.3     | 2.1 MB    | ########## | 100% 
xorg-libxau-1.0.9    | 57 KB     | ########## | 100% 
openjpeg-2.5.0       | 256 KB    | ########## | 100% 
libpng-1.6.37        | 736 KB    | ########## | 100% 
glib-tools-2.72.1    | 167 KB    | ########## | 100% 
m2w64-gcc-libs-5.3.0 | 520 KB    | ########## | 100% 
pcre-8.45            | 518 KB    | ########## | 100% 
brotli-1.0.9         | 18 KB     | ########## | 100% 
munkres-1.1.4        | 12 KB     | ########## | 100% 
qt-main-5.15.4       | 69.8 MB   | ########## | 100% 
cycler-0.11.0        | 10 KB     | ########## | 100% 
matplotlib-3.5.3     | 7 KB      | ########## | 100% 
pillow-9.2.0         | 45.4 MB   | ########## | 100% 
kiwisolver-1.4.4     | 61 KB     | ########## | 100% 
libclang-14.0.6      | 144 KB    | ########## | 100% 
tornado-6.2          | 666

In [97]:
]add Gadfly

    Updating registry at `C:\Users\dan_x\.julia\registries\General.toml`
   Resolving package versions...
   Installed Media ───────────── v0.5.0
   Installed Measures ────────── v0.3.1
   Installed StaticArraysCore ── v1.4.0
   Installed StaticArrays ────── v1.5.8
   Installed OpenSSL ─────────── v1.1.1
   Installed Contour ─────────── v0.5.7
   Installed HTTP ────────────── v1.4.0
   Installed Gadfly ──────────── v1.3.4
   Installed Loess ───────────── v0.5.4
   Installed Hexagons ────────── v0.2.0
   Installed BitFlags ────────── v0.1.5
   Installed CategoricalArrays ─ v0.10.7
   Installed DataAPI ─────────── v1.11.0
   Installed ChainRulesCore ──── v1.15.6
   Installed Tables ──────────── v1.9.0
   Installed CoupledFields ───── v0.2.0
   Installed Compose ─────────── v0.9.4
   Installed Juno ────────────── v0.8.4
   Installed Distributions ───── v0.25.75
    Updating `C:\Users\dan_x\.julia\environments\v1.7\Project.toml`
  [c91e804a] + Gadfly v1.3.4
    Updating `C:\Users\dan_x\.ju

In [98]:
using Gadfly

In [99]:
xs=1:10

1:10

In [104]:
@which xs

Main

In [105]:
ys=rand(10)

10-element Vector{Float64}:
 0.8574233920552561
 0.42602960974891013
 0.5161042272310953
 0.8694323240481162
 0.6784598107272453
 0.9603058097447011
 0.7724398314691032
 0.9456068740624068
 0.5822544770918241
 0.26868617735309597

In [106]:
plot(x=xs,y=ys)

Plot(...)